import { Post } from '../components/recent-posts/RecentPosts'

enum Categories {
  SEO = 'SEO',
  Javascript = 'javascript',
  CSS = 'CSS',
  React = 'react',
  UIandUX = 'UI and UX',
  Typescript = 'typescript',
  Elasticsearch = 'elasticsearch',
  Infrastructure = 'infrastructure',
  DevEnv = '개발환경',
  Svelt = 'svelte',
}

const posts: Post[] = [
  {
    title: '검색 엔진 최적화를 위한 설정',
    fileName: 'config-for-seo.md',
    description: '검색 엔진 최적화를 위한 설정 (Title, Meta Tag, 절대경로, robots.txt, sitemap.xml)',
    category: Categories.SEO,
    published: true,
    publishedAt: '2021-10-10',
    tags: ['Search Engine Optimization', 'SEO', '검색', '메타', '메타 태그', 'meta tag', '검색엔진', '검색엔진 최적화', 'robots.txt', 'sitemap.xml'],
    thumbnailName: 'seo-thumbnail.jpg',
  },
  {
    title: 'Tagged Template Literal',
    fileName: 'tagged-template-literal.md',
    description: 'Javascript ES6 Tagged Template Literal',
    category: Categories.Javascript,
    published: true,
    publishedAt: '2021-10-11',
    tags: ['javascript', 'tagged template', 'tagged template literal', 'es6'],
    thumbnailName: 'tagged-template-literal.jpg',
  },
  {
    title: 'Iterator and Generator',
    fileName: 'iterator-generator.md',
    description: 'Javascript ES6 Iterator & Generator, 열거형, 제너레이터 함수, generator function, yield, function*',
    category: Categories.Javascript,
    published: true,
    publishedAt: '2021-10-17',
    tags: ['javascript', 'iterator', 'iterable', 'generator', 'es6', 'function*', 'yield'],
    thumbnailName: 'iterator-generator.jpg',
  },
  {
    title: 'Proxy',
    fileName: 'proxy.md',
    description: 'Javascript ES6 Proxy, Proxy, Trap, 프락시를 이용한 객체 조작의 제어',
    category: Categories.Javascript,
    published: true,
    publishedAt: '2021-10-25',
    tags: ['javascript', 'proxy', 'trap', 'es6', '프록시'],
    thumbnailName: 'proxy.jpg',
  },
  {
    title: 'CSS Position',
    fileName: 'css-position.md',
    description: 'CSS Position (Static, Absolute, Fixed, Sticky)에 따른 고정 헤더 스타일',
    category: Categories.CSS,
    published: true,
    publishedAt: '2021-10-26',
    tags: ['css', 'position', 'static', 'absolute', 'fixed', 'sticky', 'header', 'style', '스타일', '포지션', '헤더'],
    thumbnailName: 'css-position.jpg',
  },
  {
    title: '고차 컴퍼넌트 (HOC: Higher Order Component)',
    fileName: 'hoc.md',
    description: 'React - 고차 컴퍼넌트를 이용한 컴퍼넌트의 재사용',
    category: Categories.React,
    published: true,
    publishedAt: '2021-10-30',
    tags: ['hoc', 'higher order component', '고차 컴퍼넌트', 'react', '리액트'],
    thumbnailName: 'hoc.jpg',
  },
  {
    title: 'Scroll sequence animation',
    fileName: 'scroll-sequence-animation.md',
    description: 'Apple 제품 페이지 같은 애니메이션을 구현해보자 - Scroll sequence animation',
    category: Categories.UIandUX,
    published: true,
    publishedAt: '2021-10-31',
    tags: ['scroll sequence', 'scroll sequence animation', 'ui', 'ux'],
    thumbnailName: 'scroll-sequence.jpg',
  },
  {
    title: 'Any | Unknown | Never',
    fileName: 'any-unknown-never.md',
    description: 'TypeScript - Any | Unknown | Never',
    category: Categories.Typescript,
    published: true,
    publishedAt: '2021-11-15',
    tags: ['typescript', 'any', 'unknown', 'never', '타입스크립트'],
    thumbnailName: 'ts-any-unknown-never.jpg',
  },
  {
    title: 'Elasticsearch: Full-text search (전문검색)',
    fileName: 'full-text-search.md',
    description: 'Elasticsearch를 이용한 Full-text search',
    category: Categories.Elasticsearch,
    published: true,
    publishedAt: '2021-11-16',
    tags: ['elasticsearch', 'full-text search', 'searching engine', '엘라스틱서치', '전문검색'],
    thumbnailName: 'elasticsearch-full-text-search.jpg',
  },
  {
    title: 'Nx build system 맛보기',
    fileName: 'monorepo-with-nx.md',
    description: 'Nx build system을 이용한 Monorepo 구성하기',
    category: Categories.Infrastructure,
    published: true,
    publishedAt: '2022-02-12',
    tags: ['nx', 'build', 'build system', 'monorepo', '빌드', '빌드 시스템', '모노리포'],
    thumbnailName: 'monorepo-with-nx.jpg',
  },
  {
    title: 'yarn berry로 구성하는 monorepo',
    fileName: 'yarn-berry-monorepo.md',
    description: 'yarn berry와 yarn workspaces를 이용해 monorepo 구성 - 환경 설정, 샘플 프로젝트',
    category: Categories.Infrastructure,
    published: true,
    publishedAt: '2022-02-26',
    tags: ['yarn', 'yarn berry', 'berry', 'monorepo', 'workspace', 'workspaces', '모노리포', 'zero-install'],
    thumbnailName: 'yarn-berry-monorepo.jpg',
    references: [
      {
        title: 'yarn workspaces',
        url: 'https://yarnpkg.com/features/workspaces',
      },
    ],
  },
  {
    title: 'ESLint - Plugin and Extends',
    fileName: 'eslint-plugin-and-extends.md',
    description: 'ESLint의 Plugin과 Extends의 차이는 무엇일까?',
    category: Categories.DevEnv,
    published: true,
    publishedAt: '2022-02-27',
    tags: ['개발환경', 'eslint', 'plugin', 'extends', 'eslint plugin', 'eslint extends', 'lint'],
    thumbnailName: 'eslint-plugin-and-extends.jpg',
    references: [
      {
        title: 'eslint-plugin-react Github repository',
        url: 'https://github.com/yannickcr/eslint-plugin-react/blob/master/index.js#L118-L179',
      },
    ],
  },
  {
    title: 'Focus on Button - Safari VS Chrome',
    fileName: 'focus-on-button-safari-vs-chrome.md',
    description: 'Safari, Chrome 브라우저에 따라 달라지는 button의 focus 속성',
    category: Categories.CSS,
    published: true,
    publishedAt: '2022-02-28',
    tags: ['CSS', 'focus', 'focus-within', 'focus-visible', 'safari', 'chrome', 'brower', '사파리', '크롬', '브라우저'],
    thumbnailName: 'focus-on-button.jpg',
    references: [
      {
        title: 'Clicking and focus - MDN Web Docs',
        url: 'https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#clicking_and_focus',
      },
    ],
  },
  {
    title: 'Heroku로 Node.js 애플리케이션 배포하기',
    fileName: 'deploy-nodejs-via-heroku.md',
    description: 'Heroku를 이용한 NodeJS  애플리케이션 배포하기',
    category: 'cloud',
    published: true,
    publishedAt: '2022-03-04',
    tags: ['heroku', 'node.js', 'cloud', 'cloud service', 'paas', 'deploy', '배포'],
    thumbnailName: 'deploy-node-js-via-heroku.png',
    references: [
      {
        title: 'Heroku Dev Center',
        url: 'https://devcenter.heroku.com/',
      },
    ],
  },
  {
    title: "Svelte - Let's get started",
    fileName: 'get-started-svelte.md',
    description: 'Svelte 맛보기',
    category: 'svelte',
    published: false,
    publishedAt: '2099-02-13',
    tags: ['svelte', 'frontend', 'get started'],
    thumbnailName: 'get-started-svelte.jpg',
    references: [
      {
        title: 'Svelte',
        url: 'https://svelte.dev/',
      },
      {
        title: 'Naver',
        url: 'https://naver.com/',
      },
    ],
  },
]

export default posts
