import 'normalize.css'
import '../styles/globals.scss'

import type { AppProps } from 'next/app'
import Footer from '../components/Footer/Footer'
import Head from 'next/head'
import Header from '../components/header/Header'
import blogConfig from '../config/blog.config'
import menus from '../config/menu.config'
import socialIcons from '../config/social.config'

const MainApp = ({ Component, pageProps }: AppProps) => {
  return (
    <>
      <Head>
        <title>Code Logs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header
        title={blogConfig.title}
        socialIcons={socialIcons}
        menus={menus}
      />

      <main>
        <Component {...pageProps} />
      </main>

      <Footer />
    </>
  )
}

export default MainApp
