name: Slack test

on:
  push:
    branches: [ slack_test ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Notify via Slack
        # You may pin to the exact commit or the version.
        # uses: joshmgross/send-slack-message@772aa20c5110adf514d599997db952be6d5731b1
        uses: joshmgross/send-slack-message@v1.0.1
        with:
          # The Slack message to send
          message: Code Logs built successfully.
          # A bot user access token, see https://api.slack.com/bot-users
          slack-token: ${{ secrets.SLACK_BOT_TOKEN }}
          # The Slack channel ID
          channel: ${{ secrets.SLACK_CHANNEL }}
